name: Update Baidu Flower CSV

on:
  workflow_dispatch:
  schedule:


    # 保留原来的定时：中国时间 12:00 = UTC 04:00
    - cron: '0 4 * * *'

    # 保留原来的定时：中国时间 18:00 = UTC 10:00
    - cron: '0 10 * * *'

    # 保留原来的定时：中国时间 23:59 = UTC 15:59
    - cron: '59 15 * * *'

permissions:
  contents: write

concurrency:
  group: update-baidu
  cancel-in-progress: false

jobs:
  update-baidu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
            pip install -r requirements.txt

# 先同步远程仓库，再运行脚本
      - name: Sync latest repository
        run: |
          git pull --rebase origin main

      - name: Run Baidu flower script
        run: |
          python baidu_flower_data.py

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add baidu_send_flower_data.csv
          git add baidu_send_flower_data_history.csv

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Auto update Baidu flower CSV"
          git push origin main
          fi
